### ISSUE TITLE
koa logging middleware does not log requests on swagger api routes

### ISSUE THREAD

**Issue by holmok** [carlansley/swagger2-koa#31]
I am using `koa-pino-logger` as a middleware logger that logs request and adds logger to context there are two issues:

1. request to swagger api routes are not being logged (but the swagger document routes are)
2. the logger is not on the context inside the swagger api routes

I added the logging middleware as follows:

```
r.app()
  .use(logger())
  .use(bodyParser())
  .use(ui(document))
  .listen(3000)
```

And I get the following log output (piped through `pino-colada`) when hittting the swagger docs and the api points:
```
08:35:23 ✨ request completed GET 200 /api-docs 4ms
08:35:23 🚨 request errored GET 404 /favicon.ico
08:35:23 ✨ request completed GET 404 /favicon.ico 3ms
08:35:28 ✨ request completed GET 200 /
08:35:28 ✨ request completed GET 200 /swagger-ui.css 6ms
08:35:28 ✨ request completed GET 200 /swagger-ui-standalone-preset.js 6ms
08:35:28 ✨ request completed GET 200 /swagger-ui-bundle.js 9ms
```
(no api calls)

if I try to call the logger in the following api route:

```
r.get('/health', async ctx => {
  ctx.log.info('log something')
  ctx.status = 200
  ctx.body = {
    status: 'ok'
  }
})
```

I get the following error:
```
  TypeError: Cannot read property 'info' of undefined
      at /Users/chris/work/node/topic-service/index.js:14:11
      at dispatch (/Users/chris/work/node/topic-service/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/Users/chris/work/node/topic-service/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at /Users/chris/work/node/topic-service/node_modules/koa-router/lib/router.js:346:16
      at dispatch (/Users/chris/work/node/topic-service/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at /Users/chris/work/node/topic-service/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
      at dispatch (/Users/chris/work/node/topic-service/node_modules/koa-router/lib/router.js:351:31)
      at dispatch (/Users/chris/work/node/topic-service/node_modules/koa-compose/index.js:42:32)
      at /Users/chris/work/node/topic-service/node_modules/swagger2-koa/dist/validate.js:66:15
      at dispatch (/Users/chris/work/node/topic-service/node_modules/koa-compose/index.js:42:32)
```

**Comment by holmok** [comment]
Actually, looked at the code.  I think maybe adding the option to pass a koa application to the `router` function that would allow to add middleware prior to the routes (and also metrics, error handling, etc.) . I may submit a PR to this tonight.

**Comment by holmok** [comment]
D3rp, just saw the docs on the `validate` function.  nevermind. Closing...
